repos:
  - repo: https://github.com/psf/black
    rev: 24.1.1 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/timothycrosley/isort
    rev: 5.11.5 # Replace by any tag/version: https://github.com/PyCQA/isort/tags
    hooks:
      - id: isort

  - repo: https://github.com/tmillenaar/wordwarden
    rev: v0.1.3
    hooks:
      - id: wordwarden
        name: Word Warden - Debug Statements
        entry: word_warden
        args: ["breakpoint()", ".set_trace()", "println("]
        stages: [pre-commit, pre-push]

  - repo: https://github.com/tmillenaar/wordwarden
    rev: v0.1.3
    hooks:
      - id: wordwarden
        name: Word Warden - WIP comments
        entry: word_warden
        args: ["WIP", "FIXME", "nocheckin"]
        stages: [pre-push]
