jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install dependencies
        run: |
          pip install ./[doc]
      - name: Sphinx build
        run: |
          python3 setup.py build_sphinx
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: documentation
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/pages
          force_orphan: true

