name: Build and Deploy Sphinx Documentation

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0  # Fetches full history
            fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -e ./[doc]
        working-directory: ./gridkit-py

      - name: Build Sphinx documentation
        run: bash docs/build_docs.sh
        working-directory: ./gridkit-py

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "gridkit-py/build/sphinx/html"
