name: Build and Deploy Sphinx Documentation

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "Custom tag to be displayed in doc as the gridkit version"
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
            fetch-depth: 0  # Fetches full history
            fetch-tags: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -e ./[doc]

      - name: Set GRIDKIT_DOC_BUILD_LATEST_VERSION
        run: |
          if [ -n "${{ github.event.inputs.custom_tag }}" ]; then
            echo "Using manual tag input: ${{ github.event.inputs.custom_tag }}"
            echo "GRIDKIT_DOC_BUILD_LATEST_VERSION=${{ github.event.inputs.custom_tag }}" >> $GITHUB_ENV
          else
            tag="${GITHUB_REF#refs/tags/}"
            echo "Using pushed tag: $tag"
            echo "GRIDKIT_DOC_BUILD_LATEST_VERSION=$tag" >> $GITHUB_ENV
          fi

      - name: Build Sphinx documentation
        run: bash docs/build_docs.sh

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "build/sphinx/html"
