name: Build and Deploy Sphinx Documentation

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
    inputs:
      custom_tag:
        description: "Custom tag to be displayed in doc as the gridkit version"
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -e ./[doc]

      - name: Build Sphinx documentation
        run: |
          if [ -n "${{ github.event.inputs.custom_tag }}" ]; then
            version="${{ github.event.inputs.custom_tag }}"
          else
            version="${GITHUB_REF/refs\/tags\//}"
          fi
          bash docs/build_docs.sh
          # Link landing page to the version we are currently tagging, usually the latest version
          ln "build/sphinx/html/versions/${version}/index.html" "build/sphinx/html/index.html"

      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "build/sphinx/html"
