name: Publish to PyPI
on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: pip install --upgrade setuptools wheel twine

      - name: Set the gridkit version in version.py to that of the tag
        run: sed -i -r "s|\"[[:alnum:]]+\.[[:alnum:]]+\.[[:alnum:]]+.+|\"${GITHUB_REF/refs\/tags\//}\"|" ./gridkit/version.py; cat ./gridkit/version.py

      - name: Set the gridkit version in pyproject.toml to that of the tag
        run: sed -i -r "s|version = \"[[:alnum:]]+\.[[:alnum:]]+\.[[:alnum:]]+.+|version = \"${GITHUB_REF/refs\/tags\//}\"|" ./pyproject.toml; cat ./pyproject.toml

      - name: Build distribution packages
        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.1
        with:
          user: __token__
          password: ${{ secrets.GRIDKIT_PYPI_TOKEN }}
          packages: dist/*
