name: Pytest
on:
  push:
    branches:
      - "*"

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip, setuptools, wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install ./[test]

      - name: Build rust package as wheel
        run: maturin build --manifest-path=./gridkit_rs/Cargo.toml

      - name: Install wheel of rust module
        run: pip install gridkit_rs/target/wheels/*.whl

      - name: Run pytest
        run: python -m pytest tests --cov

      - name: Run doctest
        run: python -m pytest gridkit/ --doctest-modules

      - name: Run black check
        run: python3 -m black gridkit tests --check

      - name: Run isort check
        run: python3 -m isort gridkit tests --check

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
