name: Pytest
on:
  push:
    branches:
      - "*"

jobs:
  pytest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Upgrade pip, setuptools, wheel
        run: pip install --upgrade pip setuptools wheel

      - name: Install dependencies
        run: pip install ./[test]

      - name: Run pytest
        run: python -m pytest tests

      - name: Run doctest
        run: python -m pytest gridkit/ --doctest-modules
